###############################################
######### Joint Trajectory Controller  ########
###############################################
VelocityControllers_JointTrajectoryController:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6

  constraints:
    goal_time: 5.0
    #stopped_position_tolerance: 0.4 # Defaults to 0.01
    J1:
      trajectory: 0.05
      goal:       0.01
    J2:
      trajectory: 0.05
      goal:       0.01
    J3:
      trajectory: 0.05
      goal:       0.01
    J4:
      trajectory: 0.05
      goal:       0.01
    J5:
      trajectory: 0.05
      goal:       0.01
    J6:
      trajectory: 0.05
      goal:       0.01

  gains: # Required because we're controlling a velocity interface
    J1: {p: 5,  d: 0, i: 0, i_clamp: 0}
    J2: {p: 5,  d: 0, i: 0, i_clamp: 0}
    J3: {p: 5,  d: 0, i: 0, i_clamp: 0}
    J4: {p: 5,  d: 0, i: 0, i_clamp: 0}
    J5: {p: 5,  d: 0, i: 0, i_clamp: 0}
    J6: {p: 5,  d: 0, i: 0, i_clamp: 0}

robot:
  pos_corr_gain: 0 # parameter in RAPID that needs to be set to zero to accept velocity commands alone